version: '2.0'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - /Users/bastian.bueld/Desktop/DemoProjects/KotlinMySqlDemo/docker/mysql/conf.d:/etc/mysql/conf.d
      - /Users/bastian.bueld/Desktop/DemoProjects/KotlinMySqlDemo/docker/mysql/data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
